affinity: 
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values: 
              - infra

# for fix 'E0721 05:51:25.257063       1 scraper.go:149] "Failed to scrape node" err="Get \"https://192.168.252.195:10250/metrics/resource\": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.252.195 because it doesn't contain any IP SANs" node="kind-worker2"'
args: ["--kubelet-insecure-tls"]