# https://kind.sigs.k8s.io/docs/user/configuration/
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # 1 control-plane node
  - role: control-plane
    image: kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d

  # 1 infra node
  - role: worker
    image: kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d
    extraPortMappings:
      # for loadbalance
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
    labels:
      role: infra

  # 2 application node
  - role: worker
    image: kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d
    labels:
      role: application
  - role: worker
    image: kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d
    labels:
      role: application