alertmanager:
  enabled: false
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-pushgateway:
  enabled: false

server:
  ingress:
    ## If true, Prometheus server Ingress will be created
    ##
    enabled: true
    ingressClassName: "haproxy"

    ## Prometheus server Ingress annotations
    ##
    annotations: 
      haproxy.org/ssl-redirect: "false"
    hosts: ["prometheus.example.local"]
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values: 
                - infra

