apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus.example.local:80
    isDefault: true
    jsonData:
      timeout: "300"
      queryTimeout: "300s"
      timeInterval: "1m"