{
 "title": "Prometheus",
 "description": "Prometheus Monitoring",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(prometheus_build_info,job)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Build Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_build_info{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Discovered Targets Pie",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets{job=\"$job\"}",
     "legendFormat": "{{config}}"
    }
   ]
  },
  {
   "title": "Last Reload Success",
   "type": "stat",
   "description": "Last Successful Reload\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - reloader_last_reload_success_timestamp_seconds{job=\"$job\"}",
     "legendFormat": "{{instance}} - {{ job }}"
    }
   ]
  },
  {
   "title": "Prometheus Up",
   "type": "timeseries",
   "description": "1 = Victoria can scrape prometheus\n0 = Victoria cannot scrape prometheus ( network , prometheus issues )",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Discovered Targets",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Ready",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "prometheus_ready{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Docs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "text",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 33 },
   "options": {
    "content": "# Prometheus Storage Overview\nPrometheus uses a high-performance local **Time-Series Database (TSDB)** to store metrics data. Key features include:\n\n- **Append-Only Writes**: Ensures minimal wear on storage by appending new data.\n- **Efficient Compression**: Uses optimized data structures for high compression.\n- **Retention Policies**: Allows for configurable data retention and cleanup.\n- **WAL and Blocks**: Data is written to the Write-Ahead Log (WAL) and eventually moved to block storage for durability.\n\nFor more information, visit the [Prometheus Storage Documentation](https://prometheus.io/docs/prometheus/latest/storage/).\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 33 },
   "options": {
    "content": "# Write-Ahead Log (WAL)\nThe WAL is the first stop for incoming data. It logs all new data for quick appending and crash recovery.\n\n### Key Details:\n- **Purpose**: Logs new data, enabling recovery if Prometheus crashes.\n- **Truncation**: WAL segments are truncated periodically to limit size.\n- **Replay**: During a restart, Prometheus replays the WAL to ensure all recent data is saved to storage.\n- **Checkpoint**: Creates periodic snapshots of the current data state, reducing WAL size.\n\n\n### WAL Configuration Example\n#### WAL Segment Size (`--storage.tsdb.wal-segment-size`)\nControls the size of each WAL segment file, which stores recent time-series data before it’s committed to blocks.\n\n- **Default**: `128MB`\n- **Purpose**: Larger segment sizes reduce the number of WAL files, improving read performance but increasing disk usage.\n- **Configuration Example**:\n  ```yaml\n  --storage.tsdb.wal-segment-size=64MB"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 33 },
   "options": {
    "content": "# Block Storage\nPrometheus periodically compacts recent data into **blocks** to reduce storage size and speed up querying.\n\n### Key Points:\n- **Block Creation**: By default, Prometheus creates a new block every 2 hours.\n- **Compaction**: Merges smaller blocks into larger ones, optimizing for query speed.\n- **Metadata and Indexing**: Each block has an index for quick lookups.\n\n### Example Block Storage Configuration\n```yaml\n# Configure block duration and retention time\n--storage.tsdb.min-block-duration=2h\n--storage.tsdb.retention.time=90d\n```\n\n[Choose right retention Size](https://prometheus.io/docs/prometheus/latest/storage/#right-sizing-retention-size)"
   }
  },
  { "title": "Reloader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Last Reload Success",
   "type": "timeseries",
   "description": "Whether the last reload attempt was successful\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "reloader_last_reload_successful{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "timeseries",
   "description": "Total number of reload requests.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "increase(reloader_reloads_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reload Failures",
   "type": "timeseries",
   "description": "Total number of config apply operations that failed.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "increase(reloader_config_apply_operations_failed_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(process_open_fds{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_max_fds{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Size",
   "type": "timeseries",
   "description": "Virtual memory size in bytes.\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory MAX Size",
   "type": "timeseries",
   "description": "Virtual memory size in bytes.\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Target Labels Exceeded",
   "type": "timeseries",
   "description": "This metric increases when the labels from scraped metrics for a particular scrape pool exceed the configured limits on:\n\nThe number of labels per metric series.\nThe maximum length of individual label names.\nThe maximum length of individual label values.\nWhen these limits are exceeded, Prometheus will drop the affected samples and increment this counter, indicating that some of the scraped data could not be ingested due to violating the label",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "increase(prometheus_target_scrape_pool_exceeded_label_limits_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Targets Scrape Duration Seconds",
   "type": "timeseries",
   "description": "This metric increases when the labels from scraped metrics for a particular scrape pool exceed the configured limits on:\n\nThe number of labels per metric series.\nThe maximum length of individual label names.\nThe maximum length of individual label values.\nWhen these limits are exceeded, Prometheus will drop the affected samples and increment this counter, indicating that some of the scraped data could not be ingested due to violating the label",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job='$job'}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Targets Samples Scraped Rate $interval",
   "type": "timeseries",
   "description": "The number of samples the target exposed.\n",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "rate(scrape_samples_scraped{job=\"$job\"}[$interval])",
     "legendFormat": "{{job}} - {{ instance }}"
    }
   ]
  },
  { "title": "Relabelling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Post metric Relabelling",
   "type": "timeseries",
   "description": "Metric Definition: This metric tracks the number of samples from each scrape target after relabeling has been applied. Relabeling in Prometheus allows you to modify, filter, or drop metrics as they are being scraped, based on matching label criteria.\n\nRelabeling: Relabeling is commonly used to:\n\nDrop unnecessary metrics.\nRename labels or metrics.\nControl the cardinality (number of unique time series).\nPrevent high cardinality or large volumes of unnecessary data from overwhelming Prometheus.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "scrape_samples_post_metric_relabeling{job=\"$job\", }",
     "legendFormat": "{{instance}} - post relabel"
    },
    {
     "expr": "scrape_samples_scraped{job=\"$job\"}",
     "legendFormat": "{{instance}} - pre relabel"
    }
   ]
  },
  {
   "title": "Post metric Relabelling Rate( $interval )",
   "type": "timeseries",
   "description": "Metric Definition: This metric tracks the number of samples from each scrape target after relabeling has been applied. Relabeling in Prometheus allows you to modify, filter, or drop metrics as they are being scraped, based on matching label criteria.\n\nRelabeling: Relabeling is commonly used to:\n\nDrop unnecessary metrics.\nRename labels or metrics.\nControl the cardinality (number of unique time series).\nPrevent high cardinality or large volumes of unnecessary data from overwhelming Prometheus.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "targets": [
    {
     "expr": "rate(scrape_samples_post_metric_relabeling{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series Dropped by Relabelling",
   "type": "timeseries",
   "description": "Metric Definition: This metric tracks the number of samples from each scrape target after relabeling has been applied. Relabeling in Prometheus allows you to modify, filter, or drop metrics as they are being scraped, based on matching label criteria.\n\nRelabeling: Relabeling is commonly used to:\n\nDrop unnecessary metrics.\nRename labels or metrics.\nControl the cardinality (number of unique time series).\nPrevent high cardinality or large volumes of unnecessary data from overwhelming Prometheus.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=\"$job\"} - scrape_samples_post_metric_relabeling{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "TSDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Prometheus TSDB Block Size",
   "type": "timeseries",
   "description": "The number of bytes that are currently used for local storage by all blocks.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  {
   "title": "TSDB Size Retentions",
   "type": "timeseries",
   "description": "The number of times that blocks were deleted because the maximum number of bytes was exceeded.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_size_retentions_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  {
   "title": "TSDB Time Retentions",
   "type": "timeseries",
   "description": "The number of times that blocks were deleted because the maximum time limit was exceeded.\n\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_time_retentions_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  { "title": "TSDB Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 } },
  {
   "title": "Checkpoint Creations Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_creations_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoint Creations Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_creations_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoint Deletions Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_deletions_failed_total\n{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoint Deletions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_deletions_total\n{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Compactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "Compactions triggered ",
   "type": "timeseries",
   "description": "Total number of triggered compactions for the partition.\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compactions_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  {
   "title": "Compactions triggered ",
   "type": "timeseries",
   "description": "Total number of triggered compactions for the partition.\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compactions_triggered_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  {
   "title": "Compactions Failed ",
   "type": "timeseries",
   "description": "Total number of failed compactions for the partition.\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compactions_failed_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  {
   "title": "Compactions Skipped ",
   "type": "timeseries",
   "description": "Total number of skipped compactions due to disabled auto compaction.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compactions_skipped_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  {
   "title": "Compaction Chunks Samples Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compaction_chunk_samples_count{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  {
   "title": "Compaction Chunks Samples Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compaction_chunk_samples_sum{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  {
   "title": "Tombstones cleanup seconds count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_tombstone_cleanup_seconds_count{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  { "title": "Head", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 244 } },
  {
   "title": "Head Active Appenders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 245 },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_active_appenders{job=\"$job\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chunks Storage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks_storage_size_bytes{job=\"$job\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Active Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 261 },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"$job\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Active Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 270 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_chunks_created_total{job=\"$job\"}[$interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Chunks Removed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 270 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_chunks_removed_total{job=\"$job\"}[$interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Max Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_max_time{job=\"$job\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Min Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_min_time{job=\"$job\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Out Of Order Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 286 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_out_of_order_samples_appended_total{job=\"$job\"}[$interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Samples Appended",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 286 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_samples_appended_total\n{job=\"$job\"}[$interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 294 },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series\n{job=\"$job\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Series Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 302 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_series_created_total\n{job=\"$job\"}[$interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Series Removed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 302 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_series_removed_total\n{job=\"$job\"}[$interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Series Not Found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 310 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_series_not_found_total\n{job=\"$job\"}[$interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Truncations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 318 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_truncations_total\n{job=\"$job\"}[$interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Truncations Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 326 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_truncations_failed_total\n{job=\"$job\"}[$interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 334 } },
  {
   "title": "Prometheus WAL Size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 335 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_storage_size_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}} - {{ clusterID }}"
    }
   ]
  },
  {
   "title": "WAL Truncates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 343 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_truncations_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAL Truncates Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 351 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_truncations_failed_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAL Completed Pages",
   "type": "timeseries",
   "description": "Metric Definition: The prometheus_tsdb_wal_completed_pages_total metric counts the total number of completed pages in the WAL. In the context of WAL, a page refers to a fixed-size block of data that is written to storage.\n\nCompleted Pages: This metric tracks how many pages have been successfully written and finalized in the WAL over time. This helps in understanding the volume of data being processed and how effectively the WAL is managing data writes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 359 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_completed_pages_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAL Flushed Pages",
   "type": "timeseries",
   "description": "What Does prometheus_tsdb_wal_page_flushes_total Measure?\nMetric Definition: The prometheus_tsdb_wal_page_flushes_total metric counts the total number of times that pages in the WAL have been flushed to disk. A page in this context refers to a fixed-size block of data that is written to the WAL.\n\nFlushing: Flushing a page involves writing its contents from memory to disk, ensuring that the data is safely stored and can be recovered in case of a crash. This process is critical for maintaining data integrity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 359 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_page_flushes_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAL Writes Failed Total",
   "type": "timeseries",
   "description": "What Does prometheus_tsdb_wal_writes_failed_total Measure?\nMetric Definition: The prometheus_tsdb_wal_writes_failed_total metric counts the total number of failed write attempts to the WAL. A failed write could occur for various reasons, such as:\n\nDisk space issues\nFile system permissions errors\nHardware failures\nCorrupted WAL files",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 367 },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_writes_failed_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Log Segment Index",
   "type": "timeseries",
   "description": "Metric Definition: The prometheus_tsdb_wal_segment_current metric indicates the current segment number of the WAL. The WAL is divided into segments, and each segment represents a fixed size of data that can be written. When a segment is filled, a new segment is created, and the data continues to be written.\n\nCurrent Segment: This metric reflects which segment of the WAL is currently being written to. This is particularly useful for understanding the WAL's operational state and ensuring that it is functioning correctly.Metric Definition: The prometheus_tsdb_wal_writes_failed_total metric counts the total number of failed write attempts to the WAL. A failed write could occur for various reasons, such as:\n\nDisk space issues\nFile system permissions errors\nHardware failures\nCorrupted WAL files",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 367 },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_segment_current{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 375 } },
  {
   "title": "Active Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 376 },
   "targets": [
    {
     "expr": "prometheus_agent_active_series{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agent Corruptions",
   "type": "timeseries",
   "description": "prometheus_agent_corruptions_total is useful for detecting issues with the agent’s local storage.\nIt helps you identify potential problems that could lead to data loss or delays in sending metrics to remote storage.\nA high or increasing value in this metric indicates that the agent’s storage is becoming corrupted, which might result in missing metrics or failures in remote write operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 376 },
   "targets": [
    {
     "expr": "prometheus_agent_corruptions_total{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agent Clean Start",
   "type": "timeseries",
   "description": "Value of 1: Indicates that the agent started cleanly without encountering any issues with its local storage, such as corruptions.\nValue of 0: Indicates that the agent did not have a clean start, which might suggest problems such as storage corruption, incomplete shutdowns, or other issues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 384 },
   "targets": [
    {
     "expr": "prometheus_agent_clean_start{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agent Deleted Series",
   "type": "timeseries",
   "description": "prometheus_agent_deleted_series: This metric tracks the total number of time series that have been deleted from the agent's temporary storage.\nTime series are uniquely identified streams of metric data, typically defined by a metric name and a set of labels (key-value pairs).\nDeletion of time series can happen due to retention settings, which ensure that the local buffer doesn't grow too large",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 384 },
   "targets": [
    {
     "expr": "increase(prometheus_agent_deleted_series{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agent Checkpoint Created",
   "type": "timeseries",
   "description": "prometheus_agent_checkpoint_creations_total: This metric counts the total number of checkpoints that have been created by the agent. A checkpoint is a snapshot of the state of the WAL at a particular moment, allowing the agent to manage its internal state more efficiently and safely.\nEach checkpoint helps in reducing the size of the WAL by allowing the agent to discard data that has already been safely persisted in the checkpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 392 },
   "targets": [
    {
     "expr": "increase(prometheus_agent_checkpoint_creations_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agent Checkpoint Creation Failures",
   "type": "timeseries",
   "description": "prometheus_agent_checkpoint_creations_total: This metric counts the total number of checkpoints that have been created by the agent. A checkpoint is a snapshot of the state of the WAL at a particular moment, allowing the agent to manage its internal state more efficiently and safely.\nEach checkpoint helps in reducing the size of the WAL by allowing the agent to discard data that has already been safely persisted in the checkpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 392 },
   "targets": [
    {
     "expr": "increase(prometheus_agent_checkpoint_creations_failed_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agent Checkpoint Deletions",
   "type": "timeseries",
   "description": "prometheus_agent_checkpoint_deletions_total: This metric represents the total number of checkpoints that have been deleted by the agent. Each deletion typically occurs when a new checkpoint is created, and older ones are removed to maintain efficient storage usage.Each checkpoint helps in reducing the size of the WAL by allowing the agent to discard data that has already been safely persisted in the checkpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 400 },
   "targets": [
    {
     "expr": "increase(prometheus_agent_checkpoint_deletions_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agent Checkpoint Failed Deletions",
   "type": "timeseries",
   "description": "prometheus_agent_checkpoint_deletions_total: This metric represents the total number of checkpoints that have been deleted by the agent. Each deletion typically occurs when a new checkpoint is created, and older ones are removed to maintain efficient storage usage.Each checkpoint helps in reducing the size of the WAL by allowing the agent to discard data that has already been safely persisted in the checkpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 400 },
   "targets": [
    {
     "expr": "increase(prometheus_agent_checkpoint_deletions_failed_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Remote Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 408 } },
  {
   "title": "Prometheus remote batches count",
   "type": "timeseries",
   "description": "Batch Count: This metric counts how many batches of metrics data have been successfully sent to the remote storage system.\nBatching: Prometheus batches metrics before sending them over the network to improve performance. This metric helps you understand how often Prometheus is sending batches of data, giving you insights into the behavior of the remote write process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 409 },
   "targets": [
    {
     "expr": "increase(prometheus_remote_storage_sent_batch_duration_seconds_count{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ url }}"
    }
   ]
  },
  {
   "title": "Prometheus Remote Write AVG Latency ( $interval )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 409 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_sum{job=\"$job\"}[$interval])) by (instance, url) / sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_count{job=\"$job\"}[$interval])) by (instance, url)",
     "legendFormat": "{{instance}} - {{ url }}"
    }
   ]
  },
  {
   "title": "Prometheus Remote Samples Sent ",
   "type": "timeseries",
   "description": "The total number of samples sent to remote storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 417 },
   "targets": [
    {
     "expr": "increase(prometheus_remote_storage_samples_in_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prometheus Dropped Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 417 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(prometheus_remote_storage_dropped_samples_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agent Samples Appended",
   "type": "timeseries",
   "description": "prometheus_agent_samples_appended_total: This metric counts the total number of samples that have been appended to the WAL since the agent was started.\nEach time a sample is scraped from a target, it is appended to the WAL before being sent to remote storage. This ensures that data is not lost in case of transient failures during the write process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 425 },
   "targets": [
    {
     "expr": "increase(prometheus_agent_samples_appended_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Out-of-Order Samples",
   "type": "timeseries",
   "description": "prometheus_agent_out_of_order_samples_total: This metric counts the total number of samples that have been identified as out-of-order since the agent started. Each occurrence of an out-of-order sample increments this counter.\n\nOut-of-Order Samples: These are samples that are received with timestamps that are earlier than previously recorded timestamps for the same time series. In Prometheus, a time series is defined by its metric name and label set, and samples must be recorded in chronological order.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 425 },
   "targets": [
    {
     "expr": "increase(prometheus_agent_out_of_order_samples_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prometheus Duplicate Target Sample ( $interval )",
   "type": "timeseries",
   "description": "Metric Definition: This metric tracks the total number of samples with duplicate timestamps that were encountered across all targets during scrapes. A duplicate timestamp occurs when Prometheus receives two or more samples with the same metric name, labels, and timestamp during a scrape, leading it to discard the duplicates.\n\nWhy Duplicates Occur: Duplicates typically occur when:\n\nTargets misbehave and send multiple metrics with the same timestamp in response to a scrape.\nMisconfiguration of the scraping intervals or targets.\nData push mechanisms (like using Pushgateway) send multiple samples for the same time point.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 433 },
   "targets": [
    {
     "expr": "increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agent WAL Truncates",
   "type": "timeseries",
   "description": "Understanding WAL and Truncation\nWrite-Ahead Log (WAL): The WAL is a critical component of Prometheus's data handling mechanism. It is used to record changes to the time series data before they are flushed to long-term storage (either local or remote). The WAL helps ensure data integrity and durability.\nTruncation: As data is written to the WAL, old segments that are no longer needed for recovery or are beyond the configured retention period may be truncated (deleted). This process helps manage the size of the WAL and frees up disk space.\nWhat Does prometheus_agent_truncate_duration_seconds_count Measure?\nMetric Definition: This metric counts the number of times the agent has successfully truncated the WAL and records the time taken for each truncation operation.\nCount of Truncation Events: It specifically tracks how many truncation events have occurred, providing insight into how often the WAL is being cleaned up.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 433 },
   "targets": [
    {
     "expr": "increase(prometheus_agent_truncate_duration_seconds_count{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Enqueue Retries Total",
   "type": "timeseries",
   "description": "prometheus_remote_storage: Indicates that this metric is related to the remote storage features of Prometheus.\nenqueue_retries_total: Specifically counts the total number of retries that have occurred when attempting to enqueue data for remote storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 441 },
   "targets": [
    {
     "expr": "increase(prometheus_remote_storage_enqueue_retries_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{instance}} - {{ url }}"
    }
   ]
  },
  {
   "title": "Prometheus Desired Shards",
   "type": "timeseries",
   "description": "The desired number of shards is the target number that Prometheus calculates internally to optimize the remote write process.\nMonitoring Performance: If the shards_desired metric is significantly higher than the current shards value, it might indicate that Prometheus is struggling to keep up with the data throughput and may need tuning.\nScaling: If Prometheus is handling large amounts of data, it will dynamically increase the number of shards to handle the load. Monitoring this metric helps to ensure Prometheus is effectively scaling its remote write operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 441 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_desired{job=\"$job\"}",
     "legendFormat": "{{instance}} - {{ url }}"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 449 } },
  {
   "title": "Prometheus Shards Capacity",
   "type": "timeseries",
   "description": "maximum number of shards allowed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 450 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shard_capacity{job=\"$job\"}",
     "legendFormat": "{{instance}} - {{ url }}"
    }
   ]
  },
  {
   "title": "Prometheus Shards Max Ever Used",
   "type": "timeseries",
   "description": "Max Number of Shards Used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 450 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_max{job=\"$job\"}",
     "legendFormat": "{{instance}} - {{ url }}"
    }
   ]
  },
  {
   "title": "Prometheus Shards Used",
   "type": "timeseries",
   "description": "This metric provides the current number of active shards that are being used for remote writing. The number of shards may increase or decrease dynamically based on the load and remote write performance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 458 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards{job=\"$job\"}",
     "legendFormat": "{{instance}} - {{ url }}"
    }
   ]
  }
 ]
}