kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  server.conf: |
{{ .Values.serverConfig | indent 4 }}
