apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: interview
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
  nodeSelectors:
  - matchLabels:
      role: infra
