controller:
  kind: DaemonSet
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: portMapping
              operator: In
              values: 
                - loadbalance
  daemonset:
    useHostNetwork: false
    useHostPort: true
    hostPorts:
      http: 8080
      https: 8443
      stat: 1024