{
 "title": "Node Exporter Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(up,instance)" } },
   { "name": "data_interval", "query": "1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "changes(node_boot_time_seconds{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "cpu usage | data interval $__interval",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  1 - avg by(instance) ( irate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}[$__rate_interval]))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  1 - avg ( irate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}[$__rate_interval]))\n)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "memory usage | data interval $__interval",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "( 1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / node_memory_MemTotal_bytes{instance=~\"$instance\"})\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "cpu usage (no iowait)  | data interval $__interval",
   "type": "timeseries",
   "description": "$instance",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  1 - avg by(instance) (sum by(cpu, instance) (irate(node_cpu_seconds_total{instance=~\"$instance\", mode=~\"idle|iowait\"}[$__rate_interval])))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network usage | data interval $__interval",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\nirate(node_network_receive_bytes_total{instance=~\"$instance\", device=~\"en.*|eth.*\"}[$__rate_interval]) * -1\n)",
     "legendFormat": "{{instance}}_recv"
    },
    {
     "expr": "(\n    irate(node_network_transmit_bytes_total{instance=~\"$instance\", device=~\"ens.*|eth.*\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}}_trans"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "disk usage (rootfs) | data interval $__interval",
   "type": "timeseries",
   "description": "$instance",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  1- (node_filesystem_avail_bytes{instance=~\"$instance\", mountpoint=\"/\"} / node_filesystem_size_bytes{instance=~\"$instance\", mountpoint=\"/\"})\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "disk IOPS | data interval $__interval ",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "io/s" } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (irate(node_disk_reads_completed_total{instance=~\"$instance\",device=~\"nvme.*|sd.*\"}[$__rate_interval]))\n)",
     "legendFormat": "{{instance}}_read"
    },
    {
     "expr": "(\n  sum by(instance) (irate(node_disk_writes_completed_total{instance=~\"$instance\",device=~\"nvme.*|sd.*\"}[$__rate_interval])) * -1\n)",
     "legendFormat": "{{instance}}_write"
    }
   ]
  },
  {
   "title": "disk read/write (All disk) | data interval $__interval",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\nsum by(instance) (irate(node_disk_read_bytes_total{instance=~\"$instance\",device=~\"nvme.*|sd.*\"}[$__rate_interval]))\n)",
     "legendFormat": "{{instance}}_read"
    },
    {
     "expr": "(\nsum by(instance) (irate(node_disk_written_bytes_total{instance=~\"$instance\",device=~\"nvme.*|sd.*\"}[$__rate_interval])) * -1\n)",
     "legendFormat": "{{instance}}_write"
    }
   ]
  },
  {
   "title": "disk utilization (All disk) | data interval $__interval ",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\nsum by(instance) (irate(node_disk_io_time_seconds_total{instance=~\"$instance\",device=~\"nvme.*|sd.*\"}[$__rate_interval]))\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}