{
 "title": "pod monitor",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_last_seen,pod)"
    }
   },
   {
    "name": "agg_fuct",
    "query": "max_over_time,avg_over_time,sum_over_time"
   }
  ]
 },
 "panels": [
  { "title": "README", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "select single pod to see limit" } },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "(\n  irate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval])\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_spec_cpu_quota{pod=\"$pod\",container!=\"\"}/100000",
     "legendFormat": "limit"
    },
    {
     "expr": "(\n  avg(irate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval]))\n)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "mem usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  container_memory_usage_bytes{pod=~\"$pod\",container!=\"\"}\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=\"$pod\", container!=\"\"}",
     "legendFormat": "limit"
    },
    {
     "expr": "(\n  avg(container_memory_usage_bytes{pod=~\"$pod\",container!=\"\"})\n)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "cpu usage (sum)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(\n  irate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval])\n)",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "mem usage(sum)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_usage_bytes{pod=~\"$pod\",container!=\"\"}\n)",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "cpu throttling",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum by (pod)(irate(container_cpu_cfs_throttled_seconds_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "network usage ",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum by(pod) (irate(container_network_receive_bytes_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval]))\n)* -1",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "(\n  sum by(pod) (irate(container_network_transmit_bytes_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval]))\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "disk read/write byte",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum by(pod) (irate(container_fs_writes_bytes_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval]))\n)* -1",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "(\n  sum by(pod) (irate(container_fs_reads_bytes_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval]))\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum by(pod) (irate(container_fs_writes_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval]))\n)* -1",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "(\n  sum by(pod) (irate(container_fs_reads_total{pod=~\"$pod\",container!=\"\"}[$__rate_interval]))\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FD usage | data interval $__interval | agg interval $agg_interval",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  container_file_descriptors{pod=~\"$pod\",container!=\"\"}\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "restart event",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum by(container)(changes(kube_pod_container_status_restarts_total{pod=~\"$pod\",container!=\"kube-state-metrics\"}[2m]))",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}